name: RegionRenamer
version: '1.0'
main: it.reo90.regionrenameutility.Main
api-version: '1.17'
author: Reo90
depend: [WorldGuard]
description: A powerful plugin designed to rename WorldGuard's Regions without having to recreate them.
commands:
  rgrename:
    description: Useful to rename a region.
    permission: regionrenameutility.rename
    permission-message: "&cYou are not permitted to use this command."
    aliases: [regionrename]
    usage: "&6&l» &e&lREGIONRENAME &fUsage: /renameregion <id> <newId>"